# Blockchain Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blockchain-service
  namespace: crypto-mixer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blockchain-service
  template:
    metadata:
      labels:
        app: blockchain-service
    spec:
      containers:
      - name: blockchain-service
        image: crypto-mixer/blockchain-service:latest
        ports:
        - containerPort: 3001
        envFrom:
        - configMapRef:
            name: mixer-config
        - secretRef:
            name: mixer-secrets
        env:
        - name: PORT
          value: "3001"
        - name: BTC_NODE_HOST
          valueFrom:
            secretKeyRef:
              name: blockchain-secrets
              key: BTC_NODE_HOST
        - name: BTC_RPC_USER
          valueFrom:
            secretKeyRef:
              name: blockchain-secrets
              key: BTC_RPC_USER
        - name: BTC_RPC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: blockchain-secrets
              key: BTC_RPC_PASSWORD
        - name: ETH_RPC_URL
          valueFrom:
            secretKeyRef:
              name: blockchain-secrets
              key: ETH_RPC_URL
        volumeMounts:
        - name: blockchain-keys
          mountPath: /app/keys
          readOnly: true
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "2"
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: blockchain-keys
        secret:
          secretName: blockchain-keys
          defaultMode: 0400
      # Безопасность и управление размещением
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 1001
      serviceAccountName: blockchain-service-account
      # Размещение подов на разных нодах
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - blockchain-service
              topologyKey: kubernetes.io/hostname

---
# Blockchain Service
apiVersion: v1
kind: Service
metadata:
  name: blockchain-service
  namespace: crypto-mixer
spec:
  selector:
    app: blockchain-service
  ports:
  - port: 3001
    targetPort: 3001

---
# Blockchain Secrets
apiVersion: v1
kind: Secret
metadata:
  name: blockchain-secrets
  namespace: crypto-mixer
type: Opaque
stringData:
  BTC_NODE_HOST: "your-bitcoin-node-host"
  BTC_RPC_USER: "your-bitcoin-rpc-user"
  BTC_RPC_PASSWORD: "your-bitcoin-rpc-password"
  ETH_RPC_URL: "your-ethereum-rpc-url"
  SOL_RPC_URL: "your-solana-rpc-url"
  TRON_API_URL: "your-tron-api-url"

---
# Blockchain Keys Secret
apiVersion: v1
kind: Secret
metadata:
  name: blockchain-keys
  namespace: crypto-mixer
type: Opaque
data:
  # Base64 encoded key files
  bitcoin.key: ""
  ethereum.key: ""
  solana.key: ""
  tron.key: ""

---
# Blockchain Service HPA
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: blockchain-service-hpa
  namespace: crypto-mixer
  labels:
    app: blockchain-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: blockchain-service
  minReplicas: 2
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 120
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 25
        periodSeconds: 60

---
# PodDisruptionBudget для Blockchain Service
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: blockchain-service-pdb
  namespace: crypto-mixer
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: blockchain-service

---
# ServiceAccount для Blockchain Service
apiVersion: v1
kind: ServiceAccount
metadata:
  name: blockchain-service-account
  namespace: crypto-mixer
  labels:
    app: blockchain-service