# Blockchain Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blockchain-service
  namespace: crypto-mixer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blockchain-service
  template:
    metadata:
      labels:
        app: blockchain-service
    spec:
      containers:
      - name: blockchain-service
        image: crypto-mixer/blockchain-service:latest
        ports:
        - containerPort: 3001
        envFrom:
        - configMapRef:
            name: mixer-config
        - secretRef:
            name: mixer-secrets
        env:
        - name: PORT
          value: "3001"
        - name: BTC_NODE_HOST
          valueFrom:
            secretKeyRef:
              name: blockchain-secrets
              key: BTC_NODE_HOST
        - name: BTC_RPC_USER
          valueFrom:
            secretKeyRef:
              name: blockchain-secrets
              key: BTC_RPC_USER
        - name: BTC_RPC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: blockchain-secrets
              key: BTC_RPC_PASSWORD
        - name: ETH_RPC_URL
          valueFrom:
            secretKeyRef:
              name: blockchain-secrets
              key: ETH_RPC_URL
        volumeMounts:
        - name: blockchain-keys
          mountPath: /app/keys
          readOnly: true
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "2"
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: blockchain-keys
        secret:
          secretName: blockchain-keys

---
# Blockchain Service
apiVersion: v1
kind: Service
metadata:
  name: blockchain-service
  namespace: crypto-mixer
spec:
  selector:
    app: blockchain-service
  ports:
  - port: 3001
    targetPort: 3001

---
# Blockchain Secrets
apiVersion: v1
kind: Secret
metadata:
  name: blockchain-secrets
  namespace: crypto-mixer
type: Opaque
stringData:
  BTC_NODE_HOST: "your-bitcoin-node-host"
  BTC_RPC_USER: "your-bitcoin-rpc-user"
  BTC_RPC_PASSWORD: "your-bitcoin-rpc-password"
  ETH_RPC_URL: "your-ethereum-rpc-url"
  SOL_RPC_URL: "your-solana-rpc-url"
  TRON_API_URL: "your-tron-api-url"

---
# Blockchain Keys Secret
apiVersion: v1
kind: Secret
metadata:
  name: blockchain-keys
  namespace: crypto-mixer
type: Opaque
data:
  # Base64 encoded key files
  bitcoin.key: ""
  ethereum.key: ""
  solana.key: ""
  tron.key: ""