apiVersion: v1
kind: Namespace
metadata:
  name: crypto-mixer
  labels:
    name: crypto-mixer
    app: crypto-mixer
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: crypto-mixer-quota
  namespace: crypto-mixer
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    pods: "20"
    services: "10"
    persistentvolumeclaims: "5"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: crypto-mixer-limits
  namespace: crypto-mixer
spec:
  limits:
  - default:
      cpu: 500m
      memory: 512Mi
    defaultRequest:
      cpu: 100m
      memory: 128Mi
    type: Container