# Production Secrets для Crypto Mixer
# ВАЖНО: Все значения должны быть заменены на реальные перед деплоем!

# Основные секреты приложения
apiVersion: v1
kind: Secret
metadata:
  name: mixer-secrets
  namespace: crypto-mixer
  labels:
    app: crypto-mixer
type: Opaque
stringData:
  # База данных
  DB_PASSWORD: "CHANGE_ME_SECURE_DB_PASSWORD_32_CHARS"
  DB_USER: "mixer_user"
  
  # Redis
  REDIS_PASSWORD: "CHANGE_ME_SECURE_REDIS_PASSWORD_32_CHARS"
  
  # RabbitMQ
  RABBITMQ_PASSWORD: "CHANGE_ME_SECURE_RABBITMQ_PASSWORD"
  RABBITMQ_USER: "mixer_user"
  
  # JWT и шифрование
  JWT_SECRET: "CHANGE_ME_SUPER_SECRET_JWT_KEY_64_CHARACTERS_MINIMUM_LENGTH"
  ENCRYPTION_KEY: "CHANGE_ME_AES_256_ENCRYPTION_KEY_32_BYTES_EXACTLY_HERE"
  MASTER_KEY: "CHANGE_ME_MASTER_ENCRYPTION_KEY_FOR_SENSITIVE_DATA_HERE"
  
  # Data encryption key для базы данных
  DATA_ENCRYPTION_KEY: "CHANGE_ME_DATABASE_ENCRYPTION_KEY_32_BYTES_EXACTLY"
  
  # Grafana
  GRAFANA_PASSWORD: "CHANGE_ME_GRAFANA_ADMIN_PASSWORD"
  
  # API Keys
  COINMARKETCAP_API_KEY: "your-coinmarketcap-api-key"
  COINGECKO_API_KEY: "your-coingecko-api-key"
  
  # Sentry (опционально)
  SENTRY_DSN: "https://your-sentry-dsn@sentry.io/project-id"

---
# Vault/HSM секреты
apiVersion: v1
kind: Secret
metadata:
  name: vault-secrets
  namespace: crypto-mixer
  labels:
    app: crypto-mixer
    component: vault
type: Opaque
stringData:
  VAULT_ENDPOINT: "https://vault.yourdomain.com:8200"
  VAULT_TOKEN: "CHANGE_ME_VAULT_ROOT_TOKEN_OR_SERVICE_TOKEN"
  VAULT_NAMESPACE: "crypto-mixer"
  VAULT_MOUNT_PATH: "crypto-mixer-keys"

---
# HSM секреты
apiVersion: v1
kind: Secret
metadata:
  name: hsm-secrets
  namespace: crypto-mixer
  labels:
    app: crypto-mixer
    component: hsm
type: Opaque
stringData:
  HSM_SLOT_ID: "0"
  HSM_PIN: "CHANGE_ME_HSM_PIN_CODE"
  HSM_LIBRARY_PATH: "/usr/lib/softhsm/libsofthsm2.so"
  HSM_TOKEN_LABEL: "crypto-mixer-token"

---
# Блокчейн RPC секреты
apiVersion: v1
kind: Secret
metadata:
  name: blockchain-secrets
  namespace: crypto-mixer
  labels:
    app: crypto-mixer
    component: blockchain
type: Opaque
stringData:
  # Bitcoin Core
  BTC_NODE_HOST: "bitcoin-node.yourdomain.com"
  BTC_RPC_USER: "bitcoin_rpc_user"
  BTC_RPC_PASSWORD: "CHANGE_ME_BITCOIN_RPC_PASSWORD"
  BTC_RPC_PORT: "8332"
  
  # Ethereum
  ETH_RPC_URL: "https://mainnet.infura.io/v3/YOUR_INFURA_PROJECT_ID"
  ETH_WS_URL: "wss://mainnet.infura.io/ws/v3/YOUR_INFURA_PROJECT_ID"
  
  # Solana
  SOL_RPC_URL: "https://api.mainnet-beta.solana.com"
  SOL_WS_URL: "wss://api.mainnet-beta.solana.com"
  
  # Litecoin
  LTC_RPC_URL: "http://litecoin-node.yourdomain.com:9332"
  LTC_RPC_USER: "litecoin_rpc_user"
  LTC_RPC_PASSWORD: "CHANGE_ME_LITECOIN_RPC_PASSWORD"
  
  # Dash
  DASH_RPC_URL: "http://dash-node.yourdomain.com:9998"
  DASH_RPC_USER: "dash_rpc_user"
  DASH_RPC_PASSWORD: "CHANGE_ME_DASH_RPC_PASSWORD"
  
  # Zcash
  ZEC_RPC_URL: "http://zcash-node.yourdomain.com:8232"
  ZEC_RPC_USER: "zcash_rpc_user"
  ZEC_RPC_PASSWORD: "CHANGE_ME_ZCASH_RPC_PASSWORD"
  
  # TRON
  TRON_API_URL: "https://api.trongrid.io"
  TRON_API_KEY: "your-tron-api-key"

---
# Notification секреты
apiVersion: v1
kind: Secret
metadata:
  name: notification-secrets
  namespace: crypto-mixer
  labels:
    app: crypto-mixer
    component: notifications
type: Opaque
stringData:
  # Slack
  SLACK_WEBHOOK_URL: "https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK"
  SLACK_BOT_TOKEN: "xoxb-your-slack-bot-token"
  
  # Discord
  DISCORD_WEBHOOK_URL: "https://discord.com/api/webhooks/YOUR/DISCORD/WEBHOOK"
  
  # Telegram
  TELEGRAM_BOT_TOKEN: "your-telegram-bot-token"
  TELEGRAM_CHAT_ID: "your-telegram-chat-id"
  
  # Email (SMTP)
  SMTP_HOST: "smtp.yourdomain.com"
  SMTP_PORT: "587"
  SMTP_USER: "alerts@yourdomain.com"
  SMTP_PASSWORD: "CHANGE_ME_SMTP_PASSWORD"
  
  # PagerDuty
  PAGERDUTY_INTEGRATION_KEY: "your-pagerduty-integration-key"

---
# TLS Сертификаты (для внутренних соединений)
apiVersion: v1
kind: Secret
metadata:
  name: tls-secrets
  namespace: crypto-mixer
  labels:
    app: crypto-mixer
    component: tls
type: kubernetes.io/tls
data:
  # Сертификат для внутренних соединений (base64)
  tls.crt: LS0tLS1CRUdJTi... # Замените на реальный сертификат
  tls.key: LS0tLS1CRUdJTi... # Замените на реальный приватный ключ

---
# Backup секреты
apiVersion: v1
kind: Secret
metadata:
  name: backup-secrets
  namespace: crypto-mixer
  labels:
    app: crypto-mixer
    component: backup
type: Opaque
stringData:
  # AWS S3
  AWS_ACCESS_KEY_ID: "your-aws-access-key"
  AWS_SECRET_ACCESS_KEY: "CHANGE_ME_AWS_SECRET_ACCESS_KEY"
  AWS_REGION: "us-west-2"
  S3_BUCKET: "crypto-mixer-backups"
  
  # Google Cloud Storage (альтернативно)
  GCS_SERVICE_ACCOUNT_KEY: |
    {
      "type": "service_account",
      "project_id": "your-project-id",
      "private_key_id": "key-id",
      "private_key": "-----BEGIN PRIVATE KEY-----\nYOUR_PRIVATE_KEY\n-----END PRIVATE KEY-----\n",
      "client_email": "backup@your-project.iam.gserviceaccount.com",
      "client_id": "client-id",
      "auth_uri": "https://accounts.google.com/o/oauth2/auth",
      "token_uri": "https://oauth2.googleapis.com/token"
    }
  
  # Encryption key для бэкапов
  BACKUP_ENCRYPTION_KEY: "CHANGE_ME_BACKUP_ENCRYPTION_32_CHAR_KEY"

---
# Rate Limiting и Security секреты
apiVersion: v1
kind: Secret
metadata:
  name: security-secrets
  namespace: crypto-mixer
  labels:
    app: crypto-mixer
    component: security
type: Opaque
stringData:
  # Anti-fraud API ключи
  CHAINALYSIS_API_KEY: "your-chainalysis-api-key"
  ELLIPTIC_API_KEY: "your-elliptic-api-key"
  OECD_API_KEY: "your-oecd-api-key"
  
  # Rate limiting Redis instance (если отдельный)
  RATE_LIMIT_REDIS_URL: "redis://rate-limit-redis:6379"
  RATE_LIMIT_REDIS_PASSWORD: "CHANGE_ME_RATE_LIMIT_REDIS_PASSWORD"
  
  # WAF и DDOS protection
  CLOUDFLARE_API_TOKEN: "your-cloudflare-api-token"
  
  # IP Geolocation
  MAXMIND_LICENSE_KEY: "your-maxmind-license-key"
  
  # CAPTCHA
  RECAPTCHA_SECRET_KEY: "your-recaptcha-secret-key"
  HCAPTCHA_SECRET_KEY: "your-hcaptcha-secret-key"