global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'crypto-mixer-prod'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

# Load rules
rule_files:
  - "alerts/*.yml"

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter - System metrics
  - job_name: 'node'
    static_configs:
      - targets: 
          - 'node-exporter:9100'

  # Mixer API Service
  - job_name: 'mixer-api'
    static_configs:
      - targets: ['mixer-api:3000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Blockchain Service
  - job_name: 'blockchain-service'
    static_configs:
      - targets: ['blockchain-service:3001']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Scheduler Service
  - job_name: 'scheduler-service'
    static_configs:
      - targets: ['scheduler-service:3002']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Wallet Service
  - job_name: 'wallet-service'
    static_configs:
      - targets: ['wallet-service:3003']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Monitoring Service
  - job_name: 'monitoring-service'
    static_configs:
      - targets: ['monitoring-service:3004']
    metrics_path: '/metrics'
    scrape_interval: 5s

  # Kong Gateway
  - job_name: 'kong'
    static_configs:
      - targets: ['kong:8001']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # PostgreSQL
  - job_name: 'postgresql'
    static_configs:
      - targets: ['postgres-exporter:9187']

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  # RabbitMQ
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']

  # Blackbox Exporter - Endpoint monitoring
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - https://mixer.yourdomain.com
          - https://mixer.yourdomain.com/api/v1/health
          - http://your-onion-address.onion
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115