global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: 'mixer-api'
    static_configs:
      - targets: ['mixer-api:3000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'blockchain-service'
    static_configs:
      - targets: ['blockchain-service:3001']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'wallet-service'
    static_configs:
      - targets: ['wallet-service:3003']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'monitoring-service'
    static_configs:
      - targets: ['monitoring-service:3004']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'kong'
    static_configs:
      - targets: ['kong:8001']
    metrics_path: '/metrics'
    scrape_interval: 15s

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']
    scrape_interval: 30s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093